// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdamhserdloguqftisiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYW1oc2VyZGxvZ3VxZnRpc2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTI2NzMsImV4cCI6MjA1NzA4ODY3M30.wxBuir_93S70G_F_OYPwo897pXMW-y9VESvzw1Up-9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);